spring.application.name=E-COMMERCE-REST-API-APP

# MySQL Configuration
spring.datasource.url=jdbc:mysql://mysql-container2:3306/ecommerce_db
spring.datasource.username=root
spring.datasource.password=Sandeep143
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
